spring:
  application:
    name: gateway-service-zuul
    ###### 链路跟踪 START #####
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      # 采用比率
      percentage: 1.0
    ###### END ##################
server:
  port: 80

#这里的配置表示，访问/it/** 直接重定向到http://www.ityouknow.com/**
zuul:
  routes:
# 由zuul默认注册
#    consumer:
#      path: /greeting/**
#      serviceId: consumer
    baidu:
      path: /search/**
      url: http://www.baidu.com/search/error.html
  # 开启重试功能
  retryable: true
ribbon:
  #对当前服务的重试次数
  MaxAutoRetries: 2
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8761/eureka/

