spring:
  application:
    name: spring-cloud-eureka

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 15000
  client:
    registerWithEureka: false
    fetchRegistry: false
