---
spring:
  application:
    name: producer
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
---
spring:
  profiles: producer1
server:
  port: 8771
---
spring:
  profiles: producer2
server:
  port: 8772
---