---
spring:
  application:
    name: producer
  ###### 链路跟踪 START #####
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      # 采用比率
      percentage: 1.0
  ###### END ##################
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
---
spring:
  profiles: producer1
server:
  port: 8771
---
spring:
  profiles: producer2
server:
  port: 8772
---